import 'dart:convert';

enum MediaKind { image, video, upload }
enum MediaStatus { draft, queued, processing, completed, failed, cancelled }

class MediaItem {
  const MediaItem({required this.id, required this.kind, required this.providerId, required this.providerName, required this.model, required this.prompt, this.negativePrompt='', this.sourceFilePath, this.remoteUrl, this.localPath, this.status=MediaStatus.draft, this.jobId, this.metadata=const {}, this.error, required this.createdAt, required this.updatedAt});
  final String id; final MediaKind kind; final String providerId; final String providerName; final String model; final String prompt; final String negativePrompt; final String? sourceFilePath; final String? remoteUrl; final String? localPath; final MediaStatus status; final String? jobId; final Map<String,dynamic> metadata; final String? error; final DateTime createdAt; final DateTime updatedAt;
  MediaItem copyWith({MediaStatus? status,String? remoteUrl,String? localPath,String? jobId,String? error,Map<String,dynamic>? metadata,DateTime? updatedAt})=>MediaItem(id:id,kind:kind,providerId:providerId,providerName:providerName,model:model,prompt:prompt,negativePrompt:negativePrompt,sourceFilePath:sourceFilePath,remoteUrl:remoteUrl??this.remoteUrl,localPath:localPath??this.localPath,status:status??this.status,jobId:jobId??this.jobId,metadata:metadata??this.metadata,error:error??this.error,createdAt:createdAt,updatedAt:updatedAt??this.updatedAt);
  Map<String,dynamic> toRow()=>{'id':id,'kind':kind.name,'provider_id':providerId,'provider_name':providerName,'model':model,'prompt':prompt,'negative_prompt':negativePrompt,'source_file_path':sourceFilePath,'remote_url':remoteUrl,'local_path':localPath,'status':status.name,'job_id':jobId,'metadata':jsonEncode(metadata),'error':error,'created_at':createdAt.millisecondsSinceEpoch,'updated_at':updatedAt.millisecondsSinceEpoch};
  static MediaItem fromRow(Map<String,dynamic> r)=>MediaItem(id:r['id'] as String,kind:MediaKind.values.byName(r['kind'] as String),providerId:r['provider_id'] as String,providerName:r['provider_name'] as String,model:r['model'] as String,prompt:r['prompt'] as String,negativePrompt:(r['negative_prompt']??'') as String,sourceFilePath:r['source_file_path'] as String?,remoteUrl:r['remote_url'] as String?,localPath:r['local_path'] as String?,status:MediaStatus.values.byName(r['status'] as String),jobId:r['job_id'] as String?,metadata:jsonDecode((r['metadata']??'{}') as String) as Map<String,dynamic>,error:r['error'] as String?,createdAt:DateTime.fromMillisecondsSinceEpoch(r['created_at'] as int),updatedAt:DateTime.fromMillisecondsSinceEpoch(r['updated_at'] as int));
}
